build image:
    stage: build
    image: docker:stable
    services:
        - name: docker:dind
          alias: thedockerhost
    variables:
        # Tell docker CLI how to talk to Docker daemon; see
        DOCKER_HOST: tcp://thedockerhost:2375/
        # Use the overlayfs driver for improved performance:
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
        CONTAINER_REG: "<url>"
    script:
        - docker login -u personal_acess -p <token> "$CI_REGISTRY"
        - docker build -t "$CONTAINER_REG"/bgt_db_release_manager:1.0.0 .
        - docker push "$CONTAINER_REG"/bgt_db_release_manager:1.0.0
        - docker logout